package bridge

import (
	"encoding/json"
	"strings"
	"testing"

	"github.com/wotjr1649/Clauduct/go/internal/protocol/anthropic"
)

// A one-page PDF, generated by writing the objects and the xref table directly. It says one
// token and nothing else.
const onePagePDF = "JVBERi0xLjQKMSAwIG9iago8PCAvVHlwZSAvQ2F0YWxvZyAvUGFnZXMgMiAwIFIgPj4KZW5kb2JqCjIgMCBvYmoKPDwgL1R5cGUgL1BhZ2VzIC9LaWRzIFszIDAgUl0gL0NvdW50IDEgPj4KZW5kb2JqCjMgMCBvYmoKPDwgL1R5cGUgL1BhZ2UgL1BhcmVudCAyIDAgUiAvTWVkaWFCb3ggWzAgMCA2MTIgNzkyXSAvUmVzb3VyY2VzIDw8IC9Gb250IDw8IC9GMSA0IDAgUiA+PiA+PiAvQ29udGVudHMgNSAwIFIgPj4KZW5kb2JqCjQgMCBvYmoKPDwgL1R5cGUgL0ZvbnQgL1N1YnR5cGUgL1R5cGUxIC9CYXNlRm9udCAvSGVsdmV0aWNhID4+CmVuZG9iago1IDAgb2JqCjw8IC9MZW5ndGggNDggPj4Kc3RyZWFtCkJUIC9GMSAyNCBUZiA3MiA3MDAgVGQgKENMQVVEVUNULVBERi03UTRNKSBUaiBFVAplbmRzdHJlYW0KZW5kb2JqCnhyZWYKMCA2CjAwMDAwMDAwMDAgNjU1MzUgZiAKMDAwMDAwMDAwOSAwMDAwMCBuIAowMDAwMDAwMDU4IDAwMDAwIG4gCjAwMDAwMDAxMTUgMDAwMDAgbiAKMDAwMDAwMDI0MSAwMDAwMCBuIAowMDAwMDAwMzExIDAwMDAwIG4gCnRyYWlsZXIKPDwgL1NpemUgNiAvUm9vdCAxIDAgUiA+PgpzdGFydHhyZWYKNDA5CiUlRU9GCg=="

// An attached PDF reaches the backend as an input_file data URL.
//
// The shape is not a guess and not taken from a specification. The backend was asked
// directly (clauduct-dev probe file --send) with exactly this part, and the model came back
// with a token that existed only inside the PDF -- so this asserts the shape that was
// measured to work, including the filename the backend is given.
//
// Before 2026-09-17 a document block was refused as UNSUPPORTED_CONTENT, which killed the
// turn. The client sends one whenever Read opens a PDF, so that was the common path.
func TestAnAttachedDocumentBecomesAnInputFile(t *testing.T) {
	built := imageRequest(t, `{"model":"gpt-6-astra","max_tokens":64,"stream":true,"messages":[
	  {"role":"user","content":[
	    {"type":"text","text":"what does this say"},
	    {"type":"document","source":{"type":"base64","media_type":"application/pdf","data":"`+onePagePDF+`"}}
	  ]}]}`)

	encoded, err := json.Marshal(built)
	if err != nil {
		t.Fatalf("marshal: %v", err)
	}
	for _, want := range []string{
		`"type":"input_file"`,
		`"filename":"document.pdf"`,
		`"file_data":"data:application/pdf;base64,JVBER`,
	} {
		if !strings.Contains(string(encoded), want) {
			t.Fatalf("missing %s in %s", want, encoded)
		}
	}
	// Its own entry, as an image gets, and with no text field beside it: a file is not part
	// of the sentence around it, and a struct with omitempty would have added an empty text.
	if strings.Contains(string(encoded), `"type":"input_file","text"`) {
		t.Fatalf("a text field travelled with the file: %s", encoded)
	}
	if len(built.Input) != 2 {
		t.Fatalf("entries = %d, want 2: the sentence, then the file", len(built.Input))
	}
	last := built.Input[len(built.Input)-1].Content.([]InputPart)
	if len(last) != 1 || last[0].Type != "input_file" {
		t.Fatalf("last entry = %+v, want one input_file part", last)
	}
}

// And the path that actually happens: Read returns a PDF as a tool result.
//
// The client builds that result as a text part and a document part beside it -- read out of
// claude 2.1.274 rather than assumed -- so a document has to decode inside a tool_result and
// not only at the top of a turn.
func TestADocumentInAToolResultTravelsWithIt(t *testing.T) {
	built := imageRequest(t, `{"model":"gpt-6-astra","max_tokens":64,"stream":true,
	  "tools":[{"name":"Read","description":"read","input_schema":{"type":"object"}}],
	  "messages":[
	    {"role":"user","content":"read the pdf"},
	    {"role":"assistant","content":[{"type":"tool_use","id":"call_1","name":"Read","input":{}}]},
	    {"role":"user","content":[{"type":"tool_result","tool_use_id":"call_1","content":[
	      {"type":"text","text":"1 page"},
	      {"type":"document","source":{"type":"base64","media_type":"application/pdf","data":"`+onePagePDF+`"}}
	    ]}]}]}`)

	encoded, err := json.Marshal(built)
	if err != nil {
		t.Fatalf("marshal: %v", err)
	}
	for _, want := range []string{`"type":"input_file"`, `"filename":"document.pdf"`,
		`"file_data":"data:application/pdf;base64,JVBER`, `"1 page"`} {
		if !strings.Contains(string(encoded), want) {
			t.Fatalf("missing %s in %s", want, encoded)
		}
	}
}

// What is refused, and for what.
//
// A url or file source names something this build would have to fetch or look up; a media
// type nobody has measured would send the user's attachment into an answer about nothing.
// Each refusal names the field rather than the block, because the fixes are different.
func TestAMalformedDocumentIsRefusedByWhatIsWrongWithIt(t *testing.T) {
	for _, c := range []struct {
		name, role, body, code string
	}{
		{"a url source rather than base64", "user",
			`{"type":"document","source":{"type":"url","url":"https://example.com/a.pdf"}}`,
			anthropic.CodeDocumentSourceFields},
		{"an unmeasured media type", "user",
			`{"type":"document","source":{"type":"base64","media_type":"text/plain","data":"aGk="}}`,
			anthropic.CodeUnsupportedDocument},
		{"a payload that is not base64", "user",
			`{"type":"document","source":{"type":"base64","media_type":"application/pdf","data":"not base64!"}}`,
			anthropic.CodeUnsupportedDocument},
		{"an unknown key on the block", "user",
			`{"type":"document","source":{"type":"base64","media_type":"application/pdf","data":"aGk="},"title":"x"}`,
			anthropic.CodeDocumentFields},
		{"no source at all", "user", `{"type":"document"}`, anthropic.CodeDocumentFields},
		// On an assistant turn it is a transcript that has been edited, not a request.
		{"on an assistant turn", "assistant",
			`{"type":"document","source":{"type":"base64","media_type":"application/pdf","data":"aGk="}}`,
			anthropic.CodeDocumentRole},
	} {
		t.Run(c.name, func(t *testing.T) {
			_, err := anthropic.DecodeRequest([]byte(`{"model":"gpt-6-astra","max_tokens":64,
			  "stream":true,"messages":[{"role":"` + c.role + `","content":[` + c.body + `]}]}`))
			var refusal *anthropic.RequestError
			if err == nil {
				t.Fatal("accepted a malformed document")
			}
			if !asRequestError(err, &refusal) || refusal.Code != c.code {
				t.Fatalf("err = %v, want code %s", err, c.code)
			}
		})
	}
}
