// Local metadata review of the exact public B OS-process acceptance session.
import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import assert from 'node:assert/strict';import {fileURLToPath} from 'node:url';
const here=path.dirname(fileURLToPath(import.meta.url)),id='cf295c16-790b-4aa0-aa69-9886323964c8';
const session=path.join(here,'tui-'+id),meta=JSON.parse(fs.readFileSync(path.join(session,'session.json')));
const approved='D:/AIDEV/clauduct-s36-build/repair-20260919/verification/policy-repair-20260919/interactive-e268b95d-2048-47e3-b36b-5483000541a7';
if(meta.id!==id||path.resolve(meta.profile)!==path.resolve(approved,'profile')||path.resolve(meta.project)!==path.resolve(approved,'project'))throw Error('SESSION_SCOPE');
const read=p=>{if(fs.statSync(p).size>32<<20)throw Error('INPUT_BOUND');return fs.readFileSync(p);};
const json=p=>JSON.parse(read(p)),rows=p=>read(p).toString().trim().split(/\r?\n/).filter(Boolean).map(JSON.parse),hash=p=>crypto.createHash('sha256').update(read(p)).digest('hex');
const projects=path.join(meta.profile,'projects'),parents=fs.readdirSync(projects).filter(n=>fs.existsSync(path.join(projects,n,id+'.jsonl')));
if(parents.length!==1)throw Error('TRANSCRIPT_IDENTITY');
const base=path.join(projects,parents[0],id),calls=[],results=[],texts=[];
function transcript(p,agent){for(const row of rows(p)){for(const b of Array.isArray(row.message?.content)?row.message.content:[]){
 if(b.type==='tool_use')calls.push({agent,time:row.timestamp,id:b.id,name:b.name,taskId:b.name==='TaskStop'?b.input.task_id:undefined,resume:b.name==='Workflow'?b.input.resumeFromRunId:undefined,plan:b.input?.script==='clauduct:plan-v1',command:b.name==='Bash'&&b.input.command==='C:/Windows/System32/ping.exe -n 180 127.0.0.1'?b.input.command:undefined,timeout:b.name==='Bash'?b.input.timeout:undefined});
 if(b.type==='tool_result'){const t=typeof b.content==='string'?b.content:JSON.stringify(b.content);results.push({agent,time:row.timestamp,call:b.tool_use_id,error:b.is_error===true,bytes:Buffer.byteLength(t??''),stop:t?.includes('Successfully stopped task:'),interrupted:t?.includes('User rejected tool use')||t?.includes('Interrupted'),pingOutput:t?.includes('127.0.0.1'),reused:t?.includes('completed_result_reused'),notReexecuted:t?.includes('started_not_reexecuted'),rejected:t?.includes('WORKFLOW_RECOVERY')||t?.includes('already claimed'),publicValues:[...new Set(t?.match(/S44B_[A-Z_]+=\d+/g)??[])]});}
 if(b.type==='text'&&row.type==='assistant')texts.push({agent,time:row.timestamp,values:[...new Set(b.text.match(/S44B_[A-Z_]+=\d+/g)??[])]});
}}}
transcript(base+'.jsonl','parent');const childDir=path.join(base,'subagents');
for(const n of fs.readdirSync(childDir).filter(n=>/^agent-[a-z0-9]+\.jsonl$/.test(n)))transcript(path.join(childDir,n),n.slice(6,-6));
const workflows=[];for(const n of fs.readdirSync(path.join(base,'workflows')).filter(n=>/^wf_[a-f0-9-]+\.json$/.test(n))){const wf=json(path.join(base,'workflows',n)),wd=path.join(childDir,'workflows',wf.runId),journal=path.join(wd,'journal.jsonl');
for(const child of fs.readdirSync(wd).filter(n=>/^agent-[a-z0-9]+\.jsonl$/.test(n)))transcript(path.join(wd,child),child.slice(6,-6));
workflows.push({runId:wf.runId,taskId:wf.taskId,status:wf.status,agentCount:wf.agentCount,result:wf.result,journalHash:hash(journal),events:rows(journal).map(e=>({type:e.type,agentId:e.agentId,key:e.key,time:e.timestamp??e.at,keys:Object.keys(e),result:typeof e.result==='string'&&/^S44B_[AC]=\d+$/.test(e.result)?e.result:undefined}))});}
const phases=[];for(const n of fs.readdirSync(session).filter(n=>n==='first'||/^resume-\d+$/.test(n))){const runDir=path.join(session,n),run=json(path.join(runDir,'run.json')),sd=path.join(runDir,'tmp','clauduct'),sn=fs.readdirSync(sd).filter(n=>/^status-\d+.json$/.test(n));if(sn.length!==1)throw Error('STATUS_COUNT');const s=json(path.join(sd,sn[0]));
phases.push({name:n,run,client:s.gateway.client,lifecycle:s.lifecycle,completion:s.completion,selections:s.gateway.agentSelections,persistence:s.gateway.workflowPersistence,features:s.gateway.features,totals:s.gateway.totals,os:fs.existsSync(path.join(runDir,'os-ping-observation','after.json'))?{before:json(path.join(runDir,'os-ping-observation','before.json')),after:json(path.join(runDir,'os-ping-observation','after.json'))}:undefined});}
const out={id,sha256:meta.sha256,transcriptHash:hash(base+'.jsonl'),calls,results,texts:texts.filter(x=>x.values.length),workflows,phases};
if(process.argv.includes('--assert')){
 const checks=[];const check=(name,f)=>{f();checks.push(name);};
 check('unchanged_development_binary',()=>{const build=json(path.join(here,'build.json'));for(const name of ['clauduct.exe','clauduct-hook.exe','clauduct-dev.exe'])assert.equal(hash(path.join('D:/AIDEV/clauduct-s36-build',name)),build.artifacts[name]);assert.equal(meta.sha256,build.artifacts['clauduct.exe']);});
 check('native_version_2_1_278',()=>{for(const p of phases)assert.equal(p.client.version,'2.1.278');});
 check('existing_final_regression_evidence_intact',()=>{const prior=json(path.join(here,'evidence.json'));for(const name of ['all-1789907538871.jsonl','workflow-1789908304404.jsonl']){const e=prior.checks.find(x=>x.file===name);assert.ok(e);assert.equal(e.failed.length,0);assert.equal(hash(path.join(here,name)),e.sha256);}assert.equal(prior.checks.find(x=>x.file==='all-1789907538871.jsonl').passed,1668);});
 check('two_normal_launcher_exits',()=>{assert.equal(phases.length,2);for(const p of phases){assert.equal(p.run.exit,0);assert.ok(!p.run.watchdogForced);assert.equal(p.lifecycle.reason,'native_exit');assert.equal(p.lifecycle.final,true);assert.equal(p.lifecycle.nativeReaped,true);}});
 check('no_unexpected_API_tool_or_result_failure',()=>{for(const p of phases)for(const k of ['apiFailures','nativeToolFailures','unacquiredResultsInRecent','cancelledRequests'])assert.equal(p.completion[k],0);assert.equal(phases.reduce((n,p)=>n+p.completion.nativeCancellations,0),2);assert.equal(phases.reduce((n,p)=>n+p.completion.rejectedWorkflowCalls,0),1);});
 const stops=calls.filter(x=>x.name==='TaskStop');
 check('two_actual_TaskStop_acknowledgements',()=>{assert.equal(stops.length,2);assert.deepEqual(stops.map(x=>x.taskId),['wri4ms74o','wel7owafn']);for(const stop of stops)assert.ok(results.some(x=>x.call===stop.id&&x.stop&&!x.error));});
 const os=[];
 check('OS_process_start_then_stop_then_reap',()=>{for(let i=0;i<2;i++){const p=phases[i].os;assert.ok(p);assert.equal(p.before.observerCanTerminate,false);assert.equal(p.after.observerCanTerminate,false);assert.equal(p.after.allExited,true);assert.equal(p.before.targets.length,i===0?2:4);assert.equal(p.after.targets.length,p.before.targets.length);const stop=Date.parse(stops[i].time);assert.ok(Date.parse(p.before.observed)<stop);let maximum=0;
  for(const t of p.after.targets){const before=p.before.targets.find(x=>x.pid===t.pid);assert.equal(before?.created,t.created);assert.ok(Date.parse(t.created)<Date.parse(p.before.observed));const ended=Date.parse(t.exited);assert.ok(ended>=stop);assert.ok(ended-stop<5000);assert.ok(ended-Date.parse(t.created)<120000);maximum=Math.max(maximum,ended-stop);}
  os.push({taskId:stops[i].taskId,stop:stops[i].time,processes:p.after.targets,maximumStopToExitMs:maximum});
 }});
 check('exactly_two_foreground_Bash_invocations',()=>{const bash=calls.filter(x=>x.name==='Bash');assert.equal(bash.length,2);for(const b of bash){assert.equal(b.command,'C:/Windows/System32/ping.exe -n 180 127.0.0.1');assert.equal(b.timeout,240000);}});
 const source=workflows.find(x=>x.runId==='wf_7d8da92f-56f'),resumed=workflows.find(x=>x.runId==='wf_170642f6-012'),chain=workflows.find(x=>x.runId==='wf_492ca0e4-c49');
 check('source_stopped_without_C_and_journal_unchanged',()=>{assert.equal(workflows.length,3);assert.equal(source.status,'killed');assert.equal(source.agentCount,2);assert.equal(source.journalHash,'dc905bd002928ec6c14505012750eda2b382b30ee86c62a47f8aea6263f22a5d');assert.equal(chain.status,'killed');assert.equal(chain.agentCount,1);});
 check('restart_reuses_A_does_not_repeat_B_executes_C_once',()=>{assert.equal(phases[1].persistence.failed,0);assert.equal(phases[1].persistence.restored,1);assert.equal(resumed.status,'completed');assert.equal(resumed.agentCount,1);assert.deepEqual(resumed.result.results,[{step:'A',state:'completed_result_reused',body:'S44B_A=303',agentId:'a162d7bd28c9951fd'},{step:'B',state:'started_not_reexecuted',agentId:'ac2d53e5b4e192a7a'},{step:'C',state:'completed',value:'S44B_C=144'}]);assert.equal(resumed.result.complete,false);assert.equal(resumed.events.filter(x=>x.type==='result'&&x.result==='S44B_C=144').length,1);});
 check('fixed_models_efforts_and_zero_reexecuted_source_inferences',()=>{for(const [agent,model,effort] of [['a162d7bd28c9951fd','gpt-5.6-sol','high'],['ac2d53e5b4e192a7a','gpt-5.6-terra','medium'],['a412ea78877119863','gpt-5.6-luna','max'],['a6141a2ddf3cf7fa3','gpt-5.6-terra','medium']]){const seen=phases.flatMap(p=>p.selections.recent).filter(x=>x.agent===agent);assert.ok(seen.length);for(const s of seen){assert.equal(s.effectiveModel,model);assert.equal(s.effectiveEffort,effort);}assert.equal(seen.reduce((n,s)=>n+s.backendResponses,0),1);}});
 check('duplicate_rejected_then_parent_and_new_request_recover',()=>{assert.equal(results.filter(x=>x.rejected).length,1);for(const v of ['S44B_AFTER_DENIAL=47','S44B_AFTER_STOP=53','S44B_FINAL=71'])assert.ok(texts.some(x=>x.agent==='parent'&&x.values.includes(v)));const lastStop=Date.parse(stops[1].time);assert.ok(texts.some(x=>x.agent==='parent'&&x.values.includes('S44B_FINAL=71')&&Date.parse(x.time)>lastStop));});
 out.verdict={scope:'S44 supplemental B OS execution, cancellation, reaping and restart continuation',result:'pass',checks,os,requests:phases.reduce((n,p)=>n+p.totals.completed,0),meaning:'Observed native TUI and held Windows process handles; not a universal all-environment claim'};
 for(const name of ['S44-B-OS-ACCEPTANCE.md','S44-B-COMPACT-REVIEW.md','S44-USER-ACCEPTANCE.md','REPORT.md','../../docs/v2/COMPATIBILITY.md']){const file=path.resolve(here,name);for(const m of read(file).toString().matchAll(/\]\(([^)]+)\)/g)){if(/^[a-z]+:\/\//i.test(m[1]))continue;assert.ok(fs.existsSync(path.resolve(path.dirname(file),m[1].split('#')[0])),`BROKEN_DOCUMENT_LINK ${name} ${m[1]}`);}}
}
fs.writeFileSync(path.join(here,'s44b-evidence.json'),JSON.stringify(out,null,2)+'\n');console.log(JSON.stringify(out.verdict??{...out,phases:phases.map(p=>({name:p.name,completion:p.completion,persistence:p.persistence,lifecycle:p.lifecycle,os:p.os}))}));
