package gateway

import (
	"regexp"
	"sort"
	"strings"
	"sync"
)

// What the client asked for that this bridge does not do.
//
// A beta name is never refused. That is measured, not chosen: the Node baseline records
// refusing one breaking WebFetch in a real session, because refusing a header fails the
// whole request while the feature it names is already inert against this backend.
//
// This build goes one step further and does not refuse a malformed header either, which is
// a deliberate departure from the baseline's INVALID_BETA_HEADER. The reasoning is the same
// one, applied to its own premise. The header reaches exactly one decision here, negotiated,
// which matches a trimmed name exactly -- so an empty item or a repeated one cannot change
// what is enabled. Refusing it would convert a client-side oddity with no effect into a dead
// turn, and this header is generated by the client, so the turn it kills is never the user's
// fault. It is counted instead, which tells a reader the same thing and costs nothing.
//
// What is kept is a fixed label, a bounded name or a count. The header is the client's own
// text, and this record is written to a file that outlives the session.

// nativeBetas are the names known to work through this bridge.
//
// Measured 2026-09-16: a real session sends eight of these and nothing else. The list is
// larger than that because the client sends different sets for different features.
var nativeBetas = map[string]bool{
	"claude-code-20250219":                      true,
	"interleaved-thinking-2025-05-14":           true,
	"context-management-2025-06-27":             true,
	"effort-2025-11-24":                         true,
	"redact-thinking-2026-02-12":                true,
	"prompt-caching-scope-2026-01-05":           true,
	"mid-conversation-system-2026-04-07":        true,
	"thinking-token-count-2026-05-13":           true,
	"advanced-tool-use-2025-11-20":              true,
	"tool-search-tool-2025-10-19":               true,
	"per-turn-control-2026-07-01":               true,
	"mid-conversation-output-config-2026-07-01": true,
	"web-search-2025-03-05":                     true,
	"mid-conversation-tool-changes-2026-07-01":  true,
	"oauth-2025-04-20":                          true,
}

// judgedBetas are names this project decided this bridge does not implement, each with a
// fixed label. The label is what a reader gets, never the header text.
var judgedBetas = map[string]string{
	"extended-cache-ttl-2025-04-11":               "EXTENDED_CACHE_TTL",
	"cache-diagnosis-2026-04-07":                  "CACHE_DIAGNOSIS",
	"thinking-binding-controls-2026-08-01":        "THINKING_BINDING",
	"thinking-display-updates-2026-08-18":         "THINKING_DISPLAY_UPDATES",
	"prompt-caching-evict-2026-05-12":             "CACHE_EVICT",
	"structured-outputs-2025-12-15":               "STRUCTURED_OUTPUTS",
	"fast-mode-2026-02-01":                        "FAST_MODE",
	"task-budgets-2026-03-13":                     "TASK_BUDGETS",
	"advisor-tool-2026-03-01":                     "ADVISOR_TOOL",
	"agent-memory-2026-07-22":                     "AGENT_MEMORY",
	"mcp-servers-2025-12-04":                      "MCP_SERVERS",
	"skills-2025-10-02":                           "SERVER_SKILLS",
	"files-api-2025-04-14":                        "FILES_API",
	"server-side-fallback-2026-06-01":             "SERVER_FALLBACK_V1",
	"server-side-fallback-2026-07-01":             "SERVER_FALLBACK_V2",
	"fallback-credit-2026-06-01":                  "FALLBACK_CREDIT",
	"afk-mode-2026-01-31":                         "AFK_MODE",
	"dreaming-2026-04-21":                         "DREAMING",
	"managed-agents-2026-04-01":                   "MANAGED_AGENTS",
	"user-profiles-2026-03-24":                    "USER_PROFILES",
	"token-counting-2024-11-01":                   "TOKEN_COUNTING",
	"context-hint-2026-04-09":                     "CONTEXT_HINT",
	"mid-conversation-system-clear-at-2026-08-21": "SYSTEM_CLEAR_AT",
	"compact-2026-01-12":                          "SERVER_COMPACT",
	"context-1m-2025-08-07":                       "CONTEXT_1M",
	"auto-mode-classifier-2026-07-16":             "AUTO_CLASSIFIER",
	"dangerous-tool-use-2026-09-03":               "DANGEROUS_TOOL_USE",
}

// serverDependentBetas need Anthropic's own servers, so they are inert here whatever this
// bridge does. Named rather than left to fall into "unknown": a name nobody has looked at
// and a name that has been looked at and found inert are different answers.
var serverDependentBetas = map[string]bool{
	"ccr-byoc-2025-07-29":        true,
	"ccr-triggers-2026-01-30":    true,
	"environments-2025-11-01":    true,
	"mcp-tunnels-2026-06-22":     true,
	"message-batches-2024-09-24": true,
	"message-threads-2026-08-12": true,
	"oidc-federation-2026-04-01": true,
}

// betaNameShape bounds what may be recorded. The header is the client's own text and this
// record outlives the session, so an unexpected value must not be able to grow it.
var betaNameShape = regexp.MustCompile(`^[a-z][a-z0-9-]{0,63}$`)

// betaNames is how many distinct names of one kind are kept. The baseline's eight.
const betaNames = 8

// BetaReport is what the session saw asked for.
type BetaReport struct {
	// Requests is how many requests carried the header at all.
	Requests int64 `json:"requests"`
	// Malformed is how many of those had an empty or repeated item. Counted, never refused.
	Malformed int64 `json:"malformed,omitempty"`
	// Judged are the fixed labels for names this project decided are not implemented.
	Judged []string `json:"judged,omitempty"`
	// ServerDependent are names that need Anthropic's servers and are inert here.
	ServerDependent []string `json:"serverDependent,omitempty"`
	// Unknown are names nobody here has classified, bounded in shape and count.
	Unknown []string `json:"unknown,omitempty"`
}

// betaLedger accumulates what a session was asked for.
type betaLedger struct {
	mu              sync.Mutex
	requests        int64
	malformed       int64
	judged          map[string]bool
	serverDependent map[string]bool
	unknown         map[string]bool
}

func newBetaLedger() *betaLedger {
	return &betaLedger{
		judged:          map[string]bool{},
		serverDependent: map[string]bool{},
		unknown:         map[string]bool{},
	}
}

// observe classifies one request's header. An absent header is not an observation.
func (b *betaLedger) observe(header string) {
	if header == "" {
		return
	}
	names := strings.Split(header, ",")
	seen := make(map[string]bool, len(names))
	malformed := false

	b.mu.Lock()
	defer b.mu.Unlock()
	b.requests++

	for _, raw := range names {
		name := strings.TrimSpace(raw)
		if seen[name] {
			malformed = true
			continue
		}
		seen[name] = true
		switch {
		case nativeBetas[name]:
		case judgedBetas[name] != "":
			add(b.judged, judgedBetas[name])
		case serverDependentBetas[name]:
			add(b.serverDependent, name)
		case betaNameShape.MatchString(name):
			add(b.unknown, name)
		default:
			// An empty item, or text that is not a name at all. Counted and not written
			// down: there is nothing safe to record about it. Still not refused.
			malformed = true
		}
	}
	if malformed {
		b.malformed++
	}
}

// add keeps a bounded set. Past the bound a new name is dropped rather than evicting one,
// so what a reader sees is the first names the session met and not a window that slid.
func add(set map[string]bool, name string) {
	if len(set) >= betaNames && !set[name] {
		return
	}
	set[name] = true
}

func (b *betaLedger) report() BetaReport {
	b.mu.Lock()
	defer b.mu.Unlock()
	return BetaReport{
		Requests:        b.requests,
		Malformed:       b.malformed,
		Judged:          sorted(b.judged),
		ServerDependent: sorted(b.serverDependent),
		Unknown:         sorted(b.unknown),
	}
}

func sorted(set map[string]bool) []string {
	if len(set) == 0 {
		return nil
	}
	out := make([]string, 0, len(set))
	for name := range set {
		out = append(out, name)
	}
	sort.Strings(out)
	return out
}
