package gateway

import (
	"bufio"
	"encoding/json"
	"errors"
	"io"
	"regexp"
	"strings"

	"github.com/wotjr1649/Clauduct/go/internal/protocol/bridge"
	"github.com/wotjr1649/Clauduct/go/internal/wire"
)

var errSessionSelection = errors.New("SESSION_SELECTION_UNVERIFIED")

const localCommandCaveat = "<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages or otherwise consider them in your response unless the user explicitly asks you to.</local-command-caveat>"

// localCommandCaveat287 is the engine's caveat from native 2.1.287 (measured 2026-10-02).
// Each accepted caveat is an exact engine text; user text resembling one is not.
const localCommandCaveat287 = "<local-command-caveat>The command below was run directly in Claude Code, not sent to you as a request, and its output goes straight to the user. It's recorded here as context for later messages.</local-command-caveat>"

var nativeModelChoice = regexp.MustCompile("^<local-command-stdout>Set model to `([^`]+)`(?: for this session only)? with `([a-z]+)` effort</local-command-stdout>$")

// native 2.1.287 writes "Set model to `ID`" then either " for this session only" or " and
// saved as your default for new sessions", an optional " with `EFFORT` effort", and may
// append notes (ANSI-styled lines about the environment). Without an effort the session
// keeps its effort (measured: low stayed low after a picker change).
var nativeModelChoice287 = regexp.MustCompile("^<local-command-stdout>Set model to `([^`]+)`(?: for this session only| and saved as your default for new sessions)(?: with `([a-z]+)` effort)?[^<]*</local-command-stdout>$")
var nativeModelKept = regexp.MustCompile("^<local-command-stdout>Kept model as `([^`]+)`")
var nativeEffortChoice = regexp.MustCompile(`^<local-command-stdout>Set effort level to ([a-z]+)(?: \(this session only\))?: [^<\r\n]+</local-command-stdout>$`)

type choiceRow struct {
	displayRow
	PromptID    string
	IsSidechain *bool
}

// readSessionChoice reads only newly appended native rows. A selection requires
// the engine's meta caveat and two distinct, linked rows with one prompt ID.
// User text resembling a command is insufficient. No conversation body is retained.
// An unfinished triple is reread from its first byte on the next observation.
func readSessionChoice(file io.ReadSeeker, session string, offset int64, prior bridge.Pair, selection bridge.Selection) (bridge.Pair, int64, bool, error) {
	if offset < 0 {
		return prior, offset, false, errSessionSelection
	}
	if _, err := file.Seek(offset, io.SeekStart); err != nil {
		return prior, offset, false, errSessionSelection
	}
	reader := bufio.NewReaderSize(io.LimitReader(file, 32<<20), 64<<10)
	var line []byte
	var previous choiceRow
	phase, command := 0, ""
	position, safe, tripleStart := offset, offset, offset
	oversized, changed := false, false
	for {
		part, err := reader.ReadSlice('\n')
		position += int64(len(part))
		if len(line)+len(part) > 4096 {
			oversized, line = true, nil
		} else if !oversized {
			line = append(line, part...)
		}
		if err == bufio.ErrBufferFull {
			continue
		}
		if err != nil {
			if err != io.EOF {
				return prior, safe, changed, errSessionSelection
			}
			if phase != 0 {
				safe = tripleStart
			}
			return prior, safe, changed, nil
		}
		row, text, valid := parseChoiceRow(line, session)
		valid = valid && !oversized
		linked := valid && row.UUID != previous.UUID && row.ParentUUID == previous.UUID && row.PromptID == previous.PromptID && row.Version == previous.Version
		switch {
		case valid && row.IsMeta && (text == localCommandCaveat || text == localCommandCaveat287):
			phase, tripleStart = 1, position-int64(len(line))
		case phase == 1 && linked && !row.IsMeta:
			command = selectionCommand(text)
			if command == "" {
				phase = 0
			} else {
				phase = 2
			}
		case phase == 2 && linked && !row.IsMeta:
			pair, err := parseNativeChoice(command, text, prior, selection)
			if err != nil {
				return prior, tripleStart, changed, errSessionSelection
			}
			prior, changed, phase = pair, true, 0
		default:
			if phase == 2 {
				return prior, tripleStart, changed, errSessionSelection
			}
			phase = 0
		}
		if phase == 0 {
			safe = position
			previous = choiceRow{}
		} else {
			// Keep identifiers only; the native body is never part of our state.
			previous = choiceRow{displayRow: displayRow{UUID: row.UUID, Version: row.Version}, PromptID: row.PromptID}
		}
		line, oversized = nil, false
	}
}

func parseChoiceRow(raw []byte, session string) (choiceRow, string, bool) {
	var row choiceRow
	var text string
	fields, err := wire.Fields(raw, nil)
	if err != nil {
		return row, text, false
	}
	// Decode exact keys: encoding/json's case folding must not let a second
	// spelling replace one of the engine's provenance fields.
	for key, target := range map[string]any{"type": &row.Type, "sessionId": &row.SessionID, "version": &row.Version,
		"uuid": &row.UUID, "promptId": &row.PromptID, "isSidechain": &row.IsSidechain} {
		if json.Unmarshal(fields[key], target) != nil {
			return row, text, false
		}
	}
	for key, target := range map[string]any{"isMeta": &row.IsMeta, "parentUuid": &row.ParentUUID} {
		if value, exists := fields[key]; exists && json.Unmarshal(value, target) != nil {
			return row, text, false
		}
	}
	message, err := wire.Fields(fields["message"], nil)
	if err != nil || json.Unmarshal(message["role"], &row.Message.Role) != nil || json.Unmarshal(message["content"], &text) != nil {
		return row, text, false
	}
	version := clientAgent.FindStringSubmatch("claude-cli/" + row.Version)
	valid := row.Type == "user" && row.Message.Role == "user" && row.SessionID == session &&
		row.IsSidechain != nil && !*row.IsSidechain && correlationShape.MatchString(row.UUID) && correlationShape.MatchString(row.PromptID) && len(version) == 2 && version[1] == row.Version
	return row, text, valid
}

func parseNativeChoice(command, text string, prior bridge.Pair, selection bridge.Selection) (bridge.Pair, error) {
	if text == "<local-command-stdout>Cancelled</local-command-stdout>" {
		return prior, nil
	}
	var pair bridge.Pair
	switch command {
	case "model":
		if parts := nativeModelChoice.FindStringSubmatch(text); len(parts) == 3 {
			pair = bridge.Pair{Model: parts[1], Effort: parts[2]}
		} else if parts := nativeModelChoice287.FindStringSubmatch(text); len(parts) == 3 {
			pair = bridge.Pair{Model: parts[1], Effort: parts[2]}
			if pair.Effort == "" {
				pair.Effort = prior.Effort
			}
		} else if parts := nativeModelKept.FindStringSubmatch(text); len(parts) == 2 && parts[1] == prior.Model {
			pair = prior
		}
	case "effort":
		parts := nativeEffortChoice.FindStringSubmatch(text)
		if len(parts) == 2 {
			pair = bridge.Pair{Model: prior.Model, Effort: parts[1]}
		}
	}
	// The session's account list decides; a resumed session checks its own list again.
	if !selection.ValidPair(pair) {
		return prior, errSessionSelection
	}
	return pair, nil
}

func selectionCommand(text string) string {
	for _, command := range []string{"model", "effort"} {
		prefix := "<command-name>/" + command + "</command-name>"
		if strings.HasPrefix(text, prefix) && strings.Contains(text, "<command-message>"+command+"</command-message>") && strings.HasSuffix(text, "</command-args>") {
			return command
		}
	}
	return ""
}
